config/routes.rb
Rails.application.routes.draw do
  match "reports/despesas_terapeuta" => "reports#despesas_terapeuta", as: :reports_despesas_terapeuta, via: [:get, :post]
  get 'product_cashier/index'
  match "reports/entrada_julio" => "reports#entrada_julio", as: :reports_entrada_julio, via: [:get, :post]
  get 'cashiers/produtos'
  resources :pagamentos
  match "reports/produtos" => "reports#produtos", as: :reports_produtos, via: [:get, :post]
  resources :product_movements
  resources :products
  match "reports/despesas" => "reports#despesas", as: :reports_despesas, via: [:get, :post]
  resources :events
  match "reports/Entrada" => "reports#Entrada", as: :reports_Entrada, via: [:get, :post]
  match "reports/therapist" => "reports#therapist", as: :reports_therapist, via: [:get, :post]
  get 'pages/index'
  resources :reports do
    collection { post :search, to: 'reports#therapist' }
  end
  resources :therapies
  resources :items
  resources :cashiers
  resources :schedules
  resources :clients
  resources :dashboard
  get 'clients/index'
  resources :users
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
  root :to => "dashboard#index"
  #root :to => redirect('/dashboards')
  get '/events', to: 'schedules#index'
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :client
	validates_presence_of :client

end

app/models/cashier.rb
class Cashier < ApplicationRecord
	has_many :item, dependent: :destroy
	has_many :product_movements, dependent: :destroy
	belongs_to :user, optional: true
	belongs_to :therapy, optional: true
	belongs_to :client, optional: true
	has_many :pagamento_caixa, dependent: :destroy
	has_many :event, dependent: :destroy

	enum paid: [:nao, :sim]
	enum discount: ['Não', 'Sim']
	enum paymment: ["Cartão de crédito", "Cartão de débito", "Dinheiro", "Cheque", "Tranferência Bancária", "Cortesia", "Pacote", "Permuta", "Pendente", "Vale Presente", "Pago"]
	#usar_como_dinheiro :price
	#usar_como_dinheiro :paid_value

	accepts_nested_attributes_for :item
	accepts_nested_attributes_for :client
	accepts_nested_attributes_for :product_movements
	accepts_nested_attributes_for :pagamento_caixa
	
	after_update do
		unless self.user.name == 'Julio'
			Event.find_or_initialize_by(:cashier_id => self.id).update_attributes(
				:name => self.user.name,
				:price => self.therapist_value,
				:description => "Repasse para terapeuta",
				:start => self.created_at,
			)
		end
	end

end

app/models/client.rb
class Client < ApplicationRecord
	has_many :phone_clients, dependent: :destroy
	has_one :address, dependent: :destroy
	has_one :record, dependent: :destroy
	validates :name, presence: true
	has_many :items, dependent: :destroy
	has_many :cashiers, dependent: :destroy
	has_many :schedules, dependent: :destroy
	accepts_nested_attributes_for :phone_clients, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :address
	accepts_nested_attributes_for :record, update_only: false

	#usar_como_dinheiro :credit




end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :client
  belongs_to :user
  belongs_to :therapy
  belongs_to :cashier, optional: true
  enum active: [:yes, :no]

  	def title
		client.name.to_s if client.name + "/" + 
		user.name.to_s if user
	end

	after_create do
  		Cashier.create(price: self.therapy.price, paid: :nao, client_id: self.client_id, therapy_id: self.therapy_id, user_id: self.user_id)
      cashier = Cashier.last
      Item.update(self.id, cashier_id: cashier.id)
  		
	end
end

app/models/pagamento.rb
class Pagamento < ApplicationRecord
	has_many :pagamento_caixa
end

app/models/pagamento_caixa.rb
class PagamentoCaixa < ApplicationRecord
  belongs_to :pagamento
  belongs_to :cashier
end

app/models/phone_client.rb
class PhoneClient < ApplicationRecord
  belongs_to :client, optional: true
  #deixa o campo obrigatorio
  #validates :number, presence: true

end

app/models/phone_user.rb
class PhoneUser < ApplicationRecord
  belongs_to :user, optional: true
  #deixa o campo obrigatorio
  validates :number, presence: true

  def title
  	number.to_s
  end
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :product_movements
	#validates_numericality_of :quantity, :only_integer => true, :greater_than_or_equal_to => 0

  def name_with_price
    "#{name}: R$#{price}"
  end
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :client, optional: true
  enum blood_pressure: [:normal, :alta, :baixa]

end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user
  belongs_to :client
  belongs_to :therapy

  validates :user_id, presence: true
  validates :client_id, presence: true
  validates :therapy_id, presence: true

  extend TimeSplitter::Accessors
  #split_accessor :start_time
  #split_accessor :end_time
  split_accessor :start_time, :end_time, format: "%D", time_format: "%I:%M%p"


end

app/models/therapy.rb
class Therapy < ApplicationRecord
	has_and_belongs_to_many :users

	usar_como_dinheiro :price
	has_many :items, dependent: :destroy
	has_many :cashiers, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
  enum kind: [:terapeuta, :gerente, :recepcionista, :financeiro, :tecnico]
  enum status: [:active, :inactive]

  has_many :phone_users, dependent: :destroy
  has_many :cashiers, dependent: :destroy
  has_many :items, dependent: :destroy
  has_and_belongs_to_many :therapies

  #validates :color, uniqueness: true

end

app/controllers/schedules_controller.rb
require 'therapy.rb'
require 'client.rb'
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
    @schedule = Schedule.new
    @client = Client.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
    @users = User.all
    authorize @users
  end

  # GET /schedules/1/edit
  def edit
    @users = User.all
    authorize @users
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Agendamento Cadastrado!' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to '/schedules', notice: 'Agendamento Atualizado!' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:user_id, :client_id, :therapy_id, :description, :start_time, :end_time)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/schedules/_form.html.erb
<div class="row justify-content-center">
  <div class="col-md-15">
    <div class="card">
      <header class="card-header">
        <h4 class="card-title mt-2 text-center">Novo Agendamento</h4>
      </header>
      <article class="card-body">
        <%= form_with(model: schedule, local: true) do |form| %>
          <% if schedule.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

              <ul>
              <% schedule.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

            <div class="form-row">
              <div class='col form-group'>
                <%= form.collection_select :client_id, Client.order(:name), :id, :name, { include_blank: true }, class: "selecttwo", "data-placeholder" => "Cliente" %>
              </div>
              <div class='col form-group'>
                <%= form.collection_select :user_id, User.where(kind: [:terapeuta, :gerente]), :id, :name, { include_blank: true }, class: "selecttwo", "data-placeholder" => "Terapeuta"%>
              </div>
            <div class='col form-group'>
              <%= form.collection_select :therapy_id, Therapy.order(:name), :id, :name, { include_blank: true }, class: "selecttwo", "data-placeholder" => "Terapia" %>
            </div>
          </div>

          <div class="form-group">
            <%= form.text_area :description, class: 'form-control', placeholder: "Descrição" %>
          </div>

          <div class="form-group">
            <%= form.label "Data" %>
            <%= form.datetime_select :start_time, as: :string, class: 'datepicker' %>
          </div>

          <div class="form-group">
            <%= form.label "Data" %>
            <%= form.datetime_select :end_time, class: 'datepicker' %>
            <!--<div><input type="checkbox" name="billingtoo" onclick="FillBilling(this.form)"></div>
          </div>
          <script type="text/javascript">
        function FillBilling(f) {
          if(f.billingtoo.checked == true) {
            f.schedule_end_time_date.value = f.schedule_start_time_date.value;
          }
        }

          </script>-->

          <div class="actions" align="center">
            <%= form.button "Agendar", class: "btn btn-success" %>
            <%= link_to 'Sair', schedules_path, class: 'btn btn-warning' %>
          </div>
        <% end %>
      </article> <!-- card-body end .// -->
    </div> <!-- card.// -->
  </div> <!-- col.//-->
</div> <!-- row.//-->

app/views/schedules/create.js.erb
$('.calendar').fullCalendar(
  'renderSchedule', 
  $.parseJSON("<%=j render(@schedule, format: :json).html_safe %>"),
  true
);
$('.modal').modal('hide');

app/views/schedules/edit.html.erb
<h2 align="center">Editar</h2>

<%= render 'form', schedule: @schedule %>

app/views/schedules/index.html.erb
<h5 id="notice" style="color: red" align="center"><%= notice %></h5>
<% if policy(@schedules).index? %>
	<%= render 'form', schedule: @schedule %><br>
<% end %>
<div id="example1" align="center"><br/>
<table style="width:90%;" align="center">
  <tr><th>
<div class='calendar'></div>
</th></tr></table><br><br>
</div>
<br>

app/views/schedules/show.html.erb
<h5 id="notice" style="color: red" align="center"><%= notice %></h5>
<div class="row justify-content-center">
  <div class="col-md-20">
    <div class="card">
      <header class="card-header">
        <h3 class="card-title mt-2 text-center">Detalhes do Agendamento</h3>
      </header>
      <div style="padding: 5px 25px">
      <p>
        <strong>Cliente:</strong>
        <%= @schedule.client.name %>
      </p>

      <p>
        <strong>Terapeuta:</strong>
        <%= @schedule.user.name %>
      </p>

      <p>
        <strong>Terapia:</strong>
        <%= @schedule.therapy.name %>
      </p>

      <p>
        <strong>Descrição:</strong>
        <%= @schedule.description %>
      </p>

      <p>
        <strong>Horário de inicio:</strong>
        <%= @schedule.start_time.to_formatted_s(:long) %>
      </p>

      <p>
        <strong>Horário de término:</strong>
        <%= @schedule.end_time.to_formatted_s(:long) %>
      </p>

      <div class="form-row">
        <div class="col form-group" align="center"><%= link_to 'Editar', edit_schedule_path(@schedule), class: 'btn btn-info' %></div>
        <div class="col form-group" align="center"><%= link_to 'Sair', schedules_path, class: 'btn btn-warning' %></div>
      </div>

      </div>

      </article> <!-- card-body end .// -->
    </div> <!-- card.// -->
  </div> <!-- col.//-->
</div> <!-- row.//-->