config/routes.rb
Rails.application.routes.draw do
  match "reports/despesas_terapeuta" => "reports#despesas_terapeuta", as: :reports_despesas_terapeuta, via: [:get, :post]
  get 'product_cashier/index'
  match "reports/entrada_julio" => "reports#entrada_julio", as: :reports_entrada_julio, via: [:get, :post]
  get 'cashiers/produtos'
  resources :pagamentos
  match "reports/produtos" => "reports#produtos", as: :reports_produtos, via: [:get, :post]
  resources :product_movements
  resources :products
  match "reports/despesas" => "reports#despesas", as: :reports_despesas, via: [:get, :post]
  resources :events
  match "reports/Entrada" => "reports#Entrada", as: :reports_Entrada, via: [:get, :post]
  match "reports/therapist" => "reports#therapist", as: :reports_therapist, via: [:get, :post]
  get 'pages/index'
  resources :reports do
    collection { post :search, to: 'reports#therapist' }
  end
  resources :therapies
  resources :items
  resources :cashiers
  resources :schedules
  resources :clients
  resources :dashboard
  get 'clients/index'
  resources :users
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
  root :to => "dashboard#index"
  #root :to => redirect('/dashboards')
  get '/events', to: 'schedules#index'
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :client
	validates_presence_of :client

end

app/models/cashier.rb
class Cashier < ApplicationRecord
	has_many :item, dependent: :destroy
	has_many :product_movements, dependent: :destroy
	belongs_to :user, optional: true
	belongs_to :therapy, optional: true
	belongs_to :client, optional: true
	has_many :pagamento_caixa, dependent: :destroy
	has_many :event, dependent: :destroy

	enum paid: [:nao, :sim]
	enum discount: ['Não', 'Sim']
	enum paymment: ["Cartão de crédito", "Cartão de débito", "Dinheiro", "Cheque", "Tranferência Bancária", "Cortesia", "Pacote", "Permuta", "Pendente", "Vale Presente", "Pago"]
	#usar_como_dinheiro :price
	#usar_como_dinheiro :paid_value

	accepts_nested_attributes_for :item
	accepts_nested_attributes_for :client
	accepts_nested_attributes_for :product_movements
	accepts_nested_attributes_for :pagamento_caixa
	
	after_update do
		unless self.user.name == 'Julio'
			Event.find_or_initialize_by(:cashier_id => self.id).update_attributes(
				:name => self.user.name,
				:price => self.therapist_value,
				:description => "Repasse para terapeuta",
				:start => self.created_at,
			)
		end
	end

end

app/models/client.rb
class Client < ApplicationRecord
	has_many :phone_clients, dependent: :destroy
	has_one :address, dependent: :destroy
	has_one :record, dependent: :destroy
	validates :name, presence: true
	has_many :items, dependent: :destroy
	has_many :cashiers, dependent: :destroy
	has_many :schedules, dependent: :destroy
	accepts_nested_attributes_for :phone_clients, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :address
	accepts_nested_attributes_for :record, update_only: false

	#usar_como_dinheiro :credit




end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :client
  belongs_to :user
  belongs_to :therapy
  belongs_to :cashier, optional: true
  enum active: [:yes, :no]

  	def title
		client.name.to_s if client.name + "/" + 
		user.name.to_s if user
	end

	after_create do
  		Cashier.create(price: self.therapy.price, paid: :nao, client_id: self.client_id, therapy_id: self.therapy_id, user_id: self.user_id)
      cashier = Cashier.last
      Item.update(self.id, cashier_id: cashier.id)
  		
	end
end

app/models/pagamento.rb
class Pagamento < ApplicationRecord
	has_many :pagamento_caixa
end

app/models/pagamento_caixa.rb
class PagamentoCaixa < ApplicationRecord
  belongs_to :pagamento
  belongs_to :cashier
end

app/models/phone_client.rb
class PhoneClient < ApplicationRecord
  belongs_to :client, optional: true
  #deixa o campo obrigatorio
  #validates :number, presence: true

end

app/models/phone_user.rb
class PhoneUser < ApplicationRecord
  belongs_to :user, optional: true
  #deixa o campo obrigatorio
  validates :number, presence: true

  def title
  	number.to_s
  end
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :product_movements
	#validates_numericality_of :quantity, :only_integer => true, :greater_than_or_equal_to => 0

  def name_with_price
    "#{name}: R$#{price}"
  end
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :client, optional: true
  enum blood_pressure: [:normal, :alta, :baixa]

end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user
  belongs_to :client
  belongs_to :therapy

  validates :user_id, presence: true
  validates :client_id, presence: true
  validates :therapy_id, presence: true

  extend TimeSplitter::Accessors
  #split_accessor :start_time
  #split_accessor :end_time
  split_accessor :start_time, :end_time, format: "%D", time_format: "%I:%M%p"


end

app/models/therapy.rb
class Therapy < ApplicationRecord
	has_and_belongs_to_many :users

	usar_como_dinheiro :price
	has_many :items, dependent: :destroy
	has_many :cashiers, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
  enum kind: [:terapeuta, :gerente, :recepcionista, :financeiro, :tecnico]
  enum status: [:active, :inactive]

  has_many :phone_users, dependent: :destroy
  has_many :cashiers, dependent: :destroy
  has_many :items, dependent: :destroy
  has_and_belongs_to_many :therapies

  #validates :color, uniqueness: true

end

app/controllers/therapies_controller.rb
class TherapiesController < ApplicationController
  before_action :set_therapy, only: [:show, :edit, :update, :destroy]

  # GET /therapies
  # GET /therapies.json
  def index
    @therapies = Therapy.all
    @users = User.all
    authorize @users
  end

  # GET /therapies/1
  # GET /therapies/1.json
  def show
  end

  # GET /therapies/new
  def new
    @therapy = Therapy.new
  end

  # GET /therapies/1/edit
  def edit
    @users = User.all
    authorize @users
  end

  # POST /therapies
  # POST /therapies.json
  def create
    @users = User.all
    @therapy = Therapy.new(therapy_params)

    respond_to do |format|
      if @therapy.save
        format.html { redirect_to @therapy, notice: 'Terapia Cadastrada!' }
        format.json { render :show, status: :created, location: @therapy }
      else
        format.html { render :new }
        format.json { render json: @therapy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /therapies/1
  # PATCH/PUT /therapies/1.json
  def update
    @users = User.all
    respond_to do |format|
      if @therapy.update(therapy_params)
        format.html { redirect_to @therapy, notice: 'Terapia Atualizada!' }
        format.json { render :show, status: :ok, location: @therapy }
      else
        format.html { render :edit }
        format.json { render json: @therapy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /therapies/1
  # DELETE /therapies/1.json
  def destroy
    @users = User.all
    @therapy.destroy
    respond_to do |format|
      format.html { redirect_to therapies_url, notice: 'Therapy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_therapy
      @therapy = Therapy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def therapy_params
      params.require(:therapy).permit(:name, :user_id, :price)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/therapies_helper.rb
module TherapiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/therapies/_form.html.erb
<p id="notice"><%= notice %></p>
<div class="row justify-content-center">
  <div class="col-md-20">
    <div class="card">
      <header class="card-header">
        <h3 class="card-title mt-2 text-center">Terapia</h3>
      </header>

	<div style="padding: 30px">
		<%= simple_form_for(@therapy) do |f| %>
		  <%= f.error_notification %>
		  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

		  <div class="form-inputs">
		    <%= f.input :name, label: 'Nome', class: 'form-control' %>
		    <%= f.input :price, label: 'Valor', class: 'form-control' %>
		  </div>

		  <div class="form-actions" align="center">
		    <%= f.submit 'Confirmar', class: 'btn btn-success' %>
		    <%= link_to 'Sair', therapies_path, class: 'btn btn-warning' %>
		  </div><br>
		<% end %>
	</div>

      </article> <!-- card-body end .// -->
    </div> <!-- card.// -->
  </div> <!-- col.//-->
</div> <!-- row.//-->

app/views/therapies/edit.html.erb
<h2 align="center">Editar</h2>

<%= render 'form', therapy: @therapy %>

app/views/therapies/index.html.erb
<body>
  <div id="example1" align="center">
    <p id="notice"><%= notice %></p>

    <div class="table-responsive">
      <br/>
      <h1>Terapias</h1>
      <div class="row justify-content-center">
      <%= link_to 'Cadastrar nova Terapia', new_therapy_path, class: 'btn btn-success' %>
      </div>
      <div style="width:95%">
        <table id='therapies' class='table table-striped table-bordered'>
          <thead>
            <tr>
              <th>Nome</th>
              <th>Valor</th>
              <th></th>
              <% if current_user.gerente? %>
                <th></th>
              <% end %>
            </tr>
          </thead>

          <tbody>
            <% @therapies.each do |therapy| %>
              <% inativos = ["Drenagem linfatica","Oriental massage 30'","Oriental massage 60'",'Reiki','Atualizaçao','Mas. C/ Julio','Psicoterapia','Quick','Pedras Quentes','Treinamento','Produtos','Vale Presente Realizado','Auriculo','Limpeza Energética','Formação em Yoga 1°TURMA','Abhyanga 90min','Abhyanga 60min','Shirodhara 90min','Shirodhara 60min','Mentoria Integrativa FEM','Mentoria Integrativa MAS','Foot massage com escalda pes',"Oleo massagem 30'","Oleo massagem 60'","Oleo massagem 90'",'Pacote Drenagem 4','Compra Pacote Acupuntura','Mensalidade Yoga','Compra Vale Presente','Compra de Pacote Spa','Sessão do Pacote Spa',"Reflexologia 30'",'Formação YOGA 2','Acupuntura Julio (1 vez)','Acupuntura Julio retorno','Formação Yoga 3','Shiatsu 60','Acupuntura Pacote','Terapias Reflexas','Massagem Aniversariante','Massagem Feriado','Escalda pés+Massagem','Head Massage',"Oriental massage 90'","Quarta Black ",'Compra Pacote Drenagem 5','Drenagem Facial','Acupuntura Kiyoshi', '(Antigo)Quiropraxia','Quiropraxia', 'erik atendimento'] %>
              <% if (inativos.include? therapy.name) == false %>
              <tr>
                <td><%= link_to(therapy.name, therapy) %></td>
                <td><%= therapy.price %></td>
                <td><%= link_to('Editar', edit_therapy_path(therapy), class: 'btn btn-info') %>
                </td>
                <% if current_user.gerente? %>
                    <td><%= link_to('Deletar', therapy, method: :delete, data: { confirm: 'CUIDADO! Ao deletar uma terapia, o historico e vendas relacionado a comanda também serão deletados. Tem certeza?' }, class: 'btn btn-danger') %></td>
                <% end %>
              </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <br>
  </div>
</body>
<br>

app/views/therapies/new.html.erb
<h2 align="center">Cadastrar</h2>

<%= render 'form', therapy: @therapy %>

app/views/therapies/show.html.erb
<h5 id="notice" style="color: red" align="center" style="margin: 20px"><%= notice %></h5>
<div class="row justify-content-center">
  <div class="col-md-20">
    <div class="card">
      <header class="card-header">
        <h3 class="card-title mt-2 text-center">Terapia</h3>
      </header>
      <article style="margin: 20px">
		<p>
		  <strong>Name:</strong>
		  <%= @therapy.name %>
		</p>

		<p>
		  <strong>Price:</strong>
		  <%= @therapy.price %>
		</p>

		<div class="form-row">
		<div class="col form-group" align="center"><%= link_to 'Editar', edit_therapy_path(@therapy), class: 'btn btn-info' %></div>
		<div class="col form-group" align="center"><%= link_to 'Sair', therapies_path, class: 'btn btn-warning' %></div>
		</div>

      </article> <!-- card-body end .// -->
    </div> <!-- card.// -->
  </div> <!-- col.//-->
</div> <!-- row.//-->