config/routes.rb
Rails.application.routes.draw do
  match "reports/despesas_terapeuta" => "reports#despesas_terapeuta", as: :reports_despesas_terapeuta, via: [:get, :post]
  get 'product_cashier/index'
  match "reports/entrada_julio" => "reports#entrada_julio", as: :reports_entrada_julio, via: [:get, :post]
  get 'cashiers/produtos'
  resources :pagamentos
  match "reports/produtos" => "reports#produtos", as: :reports_produtos, via: [:get, :post]
  resources :product_movements
  resources :products
  match "reports/despesas" => "reports#despesas", as: :reports_despesas, via: [:get, :post]
  resources :events
  match "reports/Entrada" => "reports#Entrada", as: :reports_Entrada, via: [:get, :post]
  match "reports/therapist" => "reports#therapist", as: :reports_therapist, via: [:get, :post]
  get 'pages/index'
  resources :reports do
    collection { post :search, to: 'reports#therapist' }
  end
  resources :therapies
  resources :items
  resources :cashiers
  resources :schedules
  resources :clients
  resources :dashboard
  get 'clients/index'
  resources :users
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
  root :to => "dashboard#index"
  #root :to => redirect('/dashboards')
  get '/events', to: 'schedules#index'
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :client
	validates_presence_of :client

end

app/models/cashier.rb
class Cashier < ApplicationRecord
	has_many :item, dependent: :destroy
	has_many :product_movements, dependent: :destroy
	belongs_to :user, optional: true
	belongs_to :therapy, optional: true
	belongs_to :client, optional: true
	has_many :pagamento_caixa, dependent: :destroy
	has_many :event, dependent: :destroy

	enum paid: [:nao, :sim]
	enum discount: ['Não', 'Sim']
	enum paymment: ["Cartão de crédito", "Cartão de débito", "Dinheiro", "Cheque", "Tranferência Bancária", "Cortesia", "Pacote", "Permuta", "Pendente", "Vale Presente", "Pago"]
	#usar_como_dinheiro :price
	#usar_como_dinheiro :paid_value

	accepts_nested_attributes_for :item
	accepts_nested_attributes_for :client
	accepts_nested_attributes_for :product_movements
	accepts_nested_attributes_for :pagamento_caixa
	
	after_update do
		unless self.user.name == 'Julio'
			Event.find_or_initialize_by(:cashier_id => self.id).update_attributes(
				:name => self.user.name,
				:price => self.therapist_value,
				:description => "Repasse para terapeuta",
				:start => self.created_at,
			)
		end
	end

end

app/models/client.rb
class Client < ApplicationRecord
	has_many :phone_clients, dependent: :destroy
	has_one :address, dependent: :destroy
	has_one :record, dependent: :destroy
	validates :name, presence: true
	has_many :items, dependent: :destroy
	has_many :cashiers, dependent: :destroy
	has_many :schedules, dependent: :destroy
	accepts_nested_attributes_for :phone_clients, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :address
	accepts_nested_attributes_for :record, update_only: false

	#usar_como_dinheiro :credit




end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :client
  belongs_to :user
  belongs_to :therapy
  belongs_to :cashier, optional: true
  enum active: [:yes, :no]

  	def title
		client.name.to_s if client.name + "/" + 
		user.name.to_s if user
	end

	after_create do
  		Cashier.create(price: self.therapy.price, paid: :nao, client_id: self.client_id, therapy_id: self.therapy_id, user_id: self.user_id)
      cashier = Cashier.last
      Item.update(self.id, cashier_id: cashier.id)
  		
	end
end

app/models/pagamento.rb
class Pagamento < ApplicationRecord
	has_many :pagamento_caixa
end

app/models/pagamento_caixa.rb
class PagamentoCaixa < ApplicationRecord
  belongs_to :pagamento
  belongs_to :cashier
end

app/models/phone_client.rb
class PhoneClient < ApplicationRecord
  belongs_to :client, optional: true
  #deixa o campo obrigatorio
  #validates :number, presence: true

end

app/models/phone_user.rb
class PhoneUser < ApplicationRecord
  belongs_to :user, optional: true
  #deixa o campo obrigatorio
  validates :number, presence: true

  def title
  	number.to_s
  end
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :product_movements
	#validates_numericality_of :quantity, :only_integer => true, :greater_than_or_equal_to => 0

  def name_with_price
    "#{name}: R$#{price}"
  end
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :client, optional: true
  enum blood_pressure: [:normal, :alta, :baixa]

end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user
  belongs_to :client
  belongs_to :therapy

  validates :user_id, presence: true
  validates :client_id, presence: true
  validates :therapy_id, presence: true

  extend TimeSplitter::Accessors
  #split_accessor :start_time
  #split_accessor :end_time
  split_accessor :start_time, :end_time, format: "%D", time_format: "%I:%M%p"


end

app/models/therapy.rb
class Therapy < ApplicationRecord
	has_and_belongs_to_many :users

	usar_como_dinheiro :price
	has_many :items, dependent: :destroy
	has_many :cashiers, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
  enum kind: [:terapeuta, :gerente, :recepcionista, :financeiro, :tecnico]
  enum status: [:active, :inactive]

  has_many :phone_users, dependent: :destroy
  has_many :cashiers, dependent: :destroy
  has_many :items, dependent: :destroy
  has_and_belongs_to_many :therapies

  #validates :color, uniqueness: true

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
  end
  def therapist
  @search = Cashier.search(params[:q])
	@cashiers = @search.result


  respond_to do |format|
      format.html

      format.pdf { render pdf: "therapist",
        header: {center: "COMPANY NAME"},
        footer: { center: "[page] of [topage]" }
      }
    end

    #def search
    #  therapist
    #  render :therapist
    #end


  end

  def Entrada
    @search = Cashier.search(params[:q])
    @cashiers = @search.result
  end

  def entrada_julio
    @search = Cashier.search(params[:q])
    @cashiers = @search.result
  end

  def despesas
    @search = Event.search(params[:q])
    @events = @search.result
  end

  def despesas_terapeuta
    @search = Event.search(params[:q])
    @events = @search.result
  end

  def produtos
    @search = ProductMovement.search(params[:q])
    @product_movements = @search.result
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reports/_gerente_produtos.html.erb
<%= search_form_for @search, url: reports_produtos_path, method: :post do |f| %>
  <div class="field">
    <%= f.label :product_id_eq, 'Produto' %>
    <%= f.select :product_id_eq, options_from_collection_for_select(Product.all, "id", "name", @search.product_id_eq), :include_blank => true %>
  
    <%= f.label :user_id_eq, 'Funcionário' %>
    <%= f.select :user_id_eq, options_from_collection_for_select(User.all, "id", "name", @search.user_id_eq), :include_blank => true %>
    </div>
  <div class="input-daterange">
    Período
    <%= f.text_field :created_at_gteq, placeholder: 'De', autocomplete: "off" %>
    <%= f.text_field :created_at_lteq, placeholder: 'Até', autocomplete: "off" %>
  </div>
  <div class="actions"><%= f.submit 'Filtrar' %></div>
<% end %>


<h1>Venda de Produtos</h1>

<table id="countit" class='table table-striped table-bordered' style="width:90%;" align="center">
  <thead>
    <tr>
      <th>Produto</th>
      <th>Valor</th>
      <th>Valor de compra</th>
      <th>Uma Forma de Pagamento</th>
      <th>Duas Formas de Pagamento</th>
      <th>Quantidade</th>
      <th>Funcionario</th>
      <th>Data da Venda</th>
    </tr>
  </thead>
  <%  a = 0 %>
  <tbody>
    <% @product_movements.order('created_at DESC').each do |product_movement| %>
	    <% if product_movement.cashier %>
	      <tr>
	        <td><%= product_movement.product.name if product_movement.product %></td>
	        <td class="count-value" style="display: none;"><%= product_movement.price.to_f * product_movement.quantity %></td>
	        <td><%= number_to_currency(product_movement.price.to_f * product_movement.quantity) %></td>
	        <td class="count-value-compra" style="display: none;"><%= product_movement.buy_value.to_f * product_movement.quantity %></td>
	        <td><%= number_to_currency(product_movement.buy_value.to_f * product_movement.quantity) %></td>
	        <td class="pagamento"><%= product_movement.cashier.paymment if product_movement.cashier.pagamento_caixa.blank? %></td>
          <td>
            <% unless product_movement.cashier.pagamento_caixa.blank? %>
              <% product_movement.cashier.pagamento_caixa.each do |pagamento_caixa|%>
                <b><%= pagamento_caixa.pagamento.name %></b>: R$<%= pagamento_caixa.value %>;
              <% end %>
            <% end %> 
           </td>
	        <td><%= product_movement.quantity %></td>
	        <td><%= product_movement.user.name if product_movement.user %></td>
	        <td><%= product_movement.created_at.strftime("%d/%m/%Y") %></td>
	      </tr>
	      <% a = a + product_movement.quantity if product_movement %>
		<% end %>    
    <% end %>
    <th>Total de Produtos Vendidos</th><th><%= a %></th>
  </tbody>
</table>
<br>
<button class="btn btn-info">Imprimir Relatório</button>

app/views/reports/_recepcionista_produtos.html.erb
<%= search_form_for @search, url: reports_produtos_path, method: :post do |f| %>
  <div class="field">
    <%= f.label :product_id_eq, 'Produto' %>
    <%= f.select :product_id_eq, options_from_collection_for_select(Product.all, "id", "name", @search.product_id_eq), :include_blank => true %>
    </div>
  <div class="input-daterange">
    Período
    <%= f.text_field :created_at_gteq, placeholder: 'De', autocomplete: "off" %>
    <%= f.text_field :created_at_lteq, placeholder: 'Até', autocomplete: "off" %>
  </div>
  <div class="actions"><%= f.submit 'Filtrar' %></div>
<% end %>


<h1>Venda de Produtos</h1>

<table id="countit" class='table table-striped table-bordered' style="width:90%;" align="center">
  <thead>
    <tr>
      <th>Produto</th>
      <th>Valor</th>
      <th>Valor de compra</th>
      <th>Uma Forma de Pagamento</th>
      <th>Duas Formas de Pagamento</th>
      <th>Quantidade</th>
      <th>Funcionario</th>
      <th>Data da Venda</th>
    </tr>
  </thead>
  <%  a = 0 %>
  <tbody>
    <% @product_movements.order('created_at DESC').each do |product_movement| %>
	    <% if product_movement.cashier %>
        <% if product_movement.user == current_user %>
	      <tr>
	        <td><%= product_movement.product.name if product_movement.product %></td>
	        <td class="count-value" style="display: none;"><%= product_movement.price.to_f * product_movement.quantity %></td>
	        <td><%= number_to_currency(product_movement.price.to_f * product_movement.quantity) %></td>
	        <td class="count-value-compra" style="display: none;"><%= product_movement.buy_value.to_f * product_movement.quantity %></td>
	        <td><%= number_to_currency(product_movement.buy_value.to_f * product_movement.quantity) %></td>
	        <td class="pagamento"><%= product_movement.cashier.paymment if product_movement.cashier.pagamento_caixa.blank? %></td>
          <td>
            <% unless product_movement.cashier.pagamento_caixa.blank? %>
              <% product_movement.cashier.pagamento_caixa.each do |pagamento_caixa|%>
                <b><%= pagamento_caixa.pagamento.name %></b>: R$<%= pagamento_caixa.value %>;
              <% end %>
            <% end %> 
           </td>
	        <td><%= product_movement.quantity %></td>
	        <td><%= product_movement.user.name if product_movement.user %></td>
	        <td><%= product_movement.created_at.strftime("%d/%m/%Y") %></td>
	      </tr>
	      <% a = a + product_movement.quantity if product_movement %>
		<% end %>
    <% end %>    
    <% end %>
    <th>Total de Produtos Vendidos</th><th><%= a %></th>
  </tbody>
</table>
<br>
<button class="btn btn-info">Imprimir Relatório</button>

app/views/reports/despesas.html.erb
<br><div id="example1" align="center"><br/>
<%= search_form_for @search, url: reports_despesas_path, method: :post do |f| %>
  <div class="field">
  	<%= f.label :paid_eq, 'Pago' %>
  	<%= f.select :paid_eq, [['Não', 'false'], ['Sim', 'true']], :include_blank => true %><br>
  </div>
  <div class="input-daterange">
    Período
    <%= f.text_field :start_gteq, placeholder: 'De', autocomplete: "off" %>
    <%= f.text_field :start_lteq, placeholder: 'Até', autocomplete: "off" %>
  </div>
  <div class="actions"><%= f.submit 'Filtrar' %></div>
<% end %>

<div class="table-responsive">

<table id="countit" class='table table-striped table-bordered' style="width:90%;" align="center">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Valor</th>
      <th>Descrição</th>
      <th>Pago</th>
      <th>Data de Vencimento</th>
    </tr>
  </thead>

  <tbody>
  <% @events.order('created_at DESC').each do |event| %>
    <tr>
      <td><%= event.name %></td>
      <td><%= number_to_currency(event.price.to_f) %></td>
      <td class="count-value" style="display: none;"><%= event.price.to_f %></td>
      <td><%= event.description %></td>
      <td><% if event.paid == false %>Não <% else %> Sim <% end %></td>
      <td><%= event.start.strftime("%d/%m/%Y") %></td>
    </tr>
  <% end %>
  </tbody>
</table>

</div>

<script language="javascript" type="text/javascript">
    var tds = document.getElementById('countit').getElementsByTagName('td');
    var sumValue = 0;
    for(var i = 0; i < tds.length; i ++) {
        if(tds[i].className == 'count-value') {
            sumValue += isNaN(tds[i].innerHTML) ? 0 : parseFloat(tds[i].innerHTML);
        }
    }
    document.getElementById('countit').innerHTML += '<tr><td><b>Valor Total</b></td><td><b>R$ ' + sumValue + '</b></td></tr>';

</script>


</div>

app/views/reports/despesas_terapeuta.html.erb
<br><div id="example1" align="center"><br/>
<%= search_form_for @search, url: reports_despesas_terapeuta_path, method: :post do |f| %>
  <div class="input-daterange">
    Período
    <%= f.text_field :start_gteq, placeholder: 'De', autocomplete: "off" %>
    <%= f.text_field :start_lteq, placeholder: 'Até', autocomplete: "off" %>
  </div>
  <div class="actions"><%= f.submit 'Filtrar' %></div>
<% end %>

<div class="table-responsive">

<table id="countit" class='table table-striped table-bordered' style="width:90%;" align="center">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Valor</th>
      <th>Descrição</th>
      <th>Pago</th>
      <th>Data</th>
    </tr>
  </thead>

  <tbody>
  <% @events.order('start DESC').each do |event| %>
  <% if event.cashier_id.blank? %>
    <tr>
      <td><%= event.name %></td>
      <td><%= number_to_currency(event.price.to_f) %></td>
      <td class="count-value" style="display: none;"><%= event.price.to_f %></td>
      <td><%= event.description %></td>
      <td><% if event.paid == false && event.cashier_id == nil %>Não <% end %><% if event.paid == true && event.cashier_id == nil %> Sim <% end %></td>
      <td><%= event.start.strftime("%d/%m/%Y") if event.start%></td>
    </tr>
  <% end %>
  <% end %>
  </tbody>
</table>

</div>

<button class="btn btn-info">Imprimir Relatório</button>
<br><br>
<script language="javascript" type="text/javascript">
    var tds = document.getElementById('countit').getElementsByTagName('td');
    var sumValue = 0;
    for(var i = 0; i < tds.length; i ++) {
        if(tds[i].className == 'count-value') {
            sumValue += isNaN(tds[i].innerHTML) ? 0 : parseFloat(tds[i].innerHTML);
        }
    }
    document.getElementById('countit').innerHTML += '<tr><td><b>Valor Total</b></td><td><b>R$ ' + sumValue + '</b></td></tr>';





        function printData()
      {
         var divToPrint=document.getElementById("countit");
         newWin= window.open("");
         newWin.document.write('<html><head><title></title><h1 align="center">Relatório de Despesas</h1>');
         newWin.document.write('<style> table, th, td {border: 1px solid #ddd;;width:100%;border-collapse: collapse;padding-left:10px;padding-right:10px;}</style>');
         newWin.document.write('</head>');
         newWin.document.write(divToPrint.outerHTML);
         newWin.print();
         newWin.close();
      }

      $('button').on('click',function(){
      printData();
      })

</script>


</div>

<br>

app/views/reports/entrada_julio.html.erb
<br><div id="example1" align="center"><br/>
<%= search_form_for @search, url: reports_entrada_julio_path, method: :post do |f| %>
  <div class="field">
    <%= f.label :therapy_name_cont, 'Terapia' %>
    <%= f.select :therapy_id_eq, options_from_collection_for_select(Therapy.all, "id", "name", @search.therapy_id_eq), :include_blank => true %>
    <%= f.label :paymment_eq, 'Forma de Pagamento' %>
    <%= f.select :paymment_eq, Cashier.paymments.to_a.map { |w| [w[0].humanize, w[1]] },
                         {:include_blank => true} %>

	<%= f.label :discount_eq, 'Desconto' %>
    <%= f.select :discount_eq, Cashier.discounts.to_a.map { |w| [w[0].humanize, w[1]] },
                         {:include_blank => true} %>
  </div>
  <div class="input-daterange">
    Período
    <%= f.text_field :created_at_gteq, placeholder: 'De', autocomplete: "off" %>
    <%= f.text_field :created_at_lteq, placeholder: 'Até', autocomplete: "off" %>
  </div>
  <div class="actions"><%= f.submit 'Filtrar' %></div>
<% end %>

<div class="table-responsive">
  <table id="countit" class='table table-striped table-bordered' style="width:90%;" align="center">
    <thead>
      <tr>
        <th>Cliente</th>
        <th>Terapia</th>
        <th>Valor da Terapia</th>
        <th>Valor Pago</th>
        <th>Uma Forma de Pagamento</th>
        <th>Duas Formas de Pagamento</th>
        <th>Desconto</th>
        <th>Data de abertura</th>
        <th>Data de fechamento</th>
      </tr>
    </thead>
    <%  a = 0 %>
    <tbody>
    <% @cashiers.order('created_at DESC').each do |cashier| %>
    	<% if cashier.sim? %>
    	<% unless cashier.user.name == 'Julio' && cashier.user.kind == 'gerente'%>
  	    <tr>
          <td><%= cashier.client.name if cashier.client %></td>
  	      <td><%= cashier.therapy.name if cashier.therapy %></td>
          <td><%= number_to_currency(cashier.price.to_f) %></td>
          <td class="count-value" style="display: none;"><%= cashier.price.to_f %></td>
  	      <td><%= number_to_currency(cashier.paid_value.to_f) %></td>
  	      <td class="count-paid" style="display: none;"><%= cashier.paid_value.to_f %></td>
  	      <td class="pagamento"><%= cashier.paymment if cashier.pagamento_caixa.blank? %></td>
          <td>
            <% unless cashier.pagamento_caixa.blank? %>
              <% cashier.pagamento_caixa.each do |pagamento_caixa|%>
                <b><%= pagamento_caixa.pagamento.name %></b>: R$<%= pagamento_caixa.value %>;
              <% end %>
            <% end %> 
           </td>
  	      <td><%= cashier.discount %></td>
  	      <td><%= cashier.created_at.strftime("%d/%m/%Y - %H:%M") %></td>
  	      <td><%= cashier.updated_at.strftime("%d/%m/%Y - %H:%M") %></td>
  	    </tr>
        <% a = a + 1 if cashier %>
  	<% end %>
  	<% end %>
    <% end %>
    <th>Total de Terapias</th><th><%= a %></th>
    </tbody>
  </table>
</div>

<button class="btn btn-info">Imprimir Relatório</button>
<br><br>
<script language="javascript" type="text/javascript">
    var tds = document.getElementById('countit').getElementsByTagName('td');
    var sumPaid = 0;
    for(var i = 0; i < tds.length; i ++) {
        if(tds[i].className == 'count-paid') {
            sumPaid += isNaN(tds[i].innerHTML) ? 0 : parseFloat(tds[i].innerHTML);
        }
    }

    var tds = document.getElementById('countit').getElementsByTagName('td');
    var sumValue = 0;
    for(var i = 0; i < tds.length; i ++) {
        if(tds[i].className == 'count-value') {
            sumValue += isNaN(tds[i].innerHTML) ? 0 : parseFloat(tds[i].innerHTML);
        }
    }
    document.getElementById('countit').innerHTML += '<tr><td><b>Valor Total</b></td><td><b>R$ ' + sumValue + '</b></td></tr>';

    document.getElementById('countit').innerHTML += '<tr><td><b>Valor Total Pago</b></td><td><b>R$ ' + sumPaid + '</b></td></tr>';

    var difValuePaid = sumValue - sumPaid

    document.getElementById('countit').innerHTML += '<tr><td><b>Valor Total em Desconto</b></td><td><b>R$ ' + difValuePaid + '</b></td></tr>';





    function printData()
      {
         var divToPrint=document.getElementById("countit");
         newWin= window.open("");
         newWin.document.write('<html><head><title></title> <h1 align="center">Relatório de Entradas(Sem Júlio)</h1> <%=  %>');
         newWin.document.write('<style> table, th, td {border: 1px solid #ddd;;width:100%;border-collapse: collapse;padding-left:10px;padding-right:10px;}</style>');
         newWin.document.write('</head>');
         newWin.document.write(divToPrint.outerHTML);
         newWin.print();
         newWin.close();
      }

      $('button').on('click',function(){
      printData();
      })
</script>


</div>
<br>

app/views/reports/therapist.html.erb
<br><div id="example1" align="center"><br/>

<%= search_form_for @search, url: reports_therapist_path, method: :post do |f| %>
  <div class="field">
    <%= f.label :user_name_cont, 'Terapeuta' %>
    <%= f.select :user_id_eq, options_from_collection_for_select(User.where(kind: [:terapeuta, :gerente]), "id", "name", @search.therapy_id_eq), :include_blank => true, class: "selecttwo" %>
  </div>
  <div class="input-daterange">
    Período
    <%= f.text_field :created_at_gteq, placeholder: 'De', autocomplete: "off" %>
    <%= f.text_field :created_at_lteq, placeholder: 'Até', autocomplete: "off" %>
  </div>
  <div class="actions"><%= f.submit 'Filtrar' %></div>
<% end %>

<table id="countit" class='table table-striped table-bordered' style="width:90%;" align="center">
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Terapeuta</th>
      <th>Terapia</th>
      <th>Valor Pago</th>
      <th>Uma Forma de Pagamento</th>
      <th>Duas Formas de Pagamento</th>
      <th>Valor de Repasse</th>
      <th>Data de abertura</th>
      <th>Data de fechamento</th>
    </tr>
  </thead>

  <tbody>
  <% @cashiers.order('created_at DESC').each do |cashier| %>
  <% unless cashier.therapy.blank? %>
    <tr>
      <td><%= cashier.client.name if cashier.client%></td>
      <td><%= cashier.user.name if cashier.user%></td>
      <td><%= cashier.therapy.name if cashier.therapy%></td>
      <td><%= number_to_currency(cashier.paid_value.to_f) %></td>
      <td class="count-me" style="display: none;"><%= cashier.paid_value.to_f %></td>
      <td><%= cashier.paymment if cashier.pagamento_caixa.blank? %></td>
      <td>
      <% unless cashier.pagamento_caixa.blank? %>
        <% cashier.pagamento_caixa.each do |pagamento_caixa|%>
          <b><%= pagamento_caixa.pagamento.name %></b>: R$<%= pagamento_caixa.value %>;
        <% end %>
      <% end %> 
     </td>
      <td><%= number_to_currency(cashier.therapist_value.to_f) %></td>
      <td class="count-therapist" style="display: none;"><%= cashier.therapist_value.to_f %></td>
      <td><%= cashier.created_at.strftime("%d/%m/%Y - %H:%M") %></td>
      <td><%= cashier.updated_at.strftime("%d/%m/%Y - %H:%M") %></td>
    </tr>
  <% end %>
  <% end %>
  </tbody>
</table>
<button class="btn btn-info">Imprimir Relatório</button><br>
<br>
</div>
<br>

<script language="javascript" type="text/javascript">
    var tds = document.getElementById('countit').getElementsByTagName('td');
    var sum = 0;
    for(var i = 0; i < tds.length; i ++) {
        if(tds[i].className == 'count-me') {
            sum += isNaN(tds[i].innerHTML) ? 0 : parseFloat(tds[i].innerHTML);
        }
    }
    document.getElementById('countit').innerHTML += '<tr><th>Total Pago</th><td>R$ ' + sum + '</td></tr>';
</script>

<script language="javascript" type="text/javascript">
    var tds = document.getElementById('countit').getElementsByTagName('td');
    var sum = 0;
    for(var i = 0; i < tds.length; i ++) {
        if(tds[i].className == 'count-therapist') {
            sum += isNaN(tds[i].innerHTML) ? 0 : parseFloat(tds[i].innerHTML);
        }
    }
    document.getElementById('countit').innerHTML += '<tr><th>Total de Repasse</th><td>R$ ' + sum + '</td></tr>';



        function printData()
      {
         var divToPrint=document.getElementById("countit");
         newWin= window.open("");
         newWin.document.write('<html><head><title></title> <h1 align="center">Relatório do Terapeuta</h1> <%=  %>');
         newWin.document.write('<style> table, th, td {border: 1px solid #ddd;;width:100%;border-collapse: collapse;padding-left:10px;padding-right:10px;}</style>');
         newWin.document.write('</head>');
         newWin.document.write(divToPrint.outerHTML);
         newWin.print();
         newWin.close();
      }

      $('button').on('click',function(){
      printData();
      })
</script>